services:
  proxy:
    image: nginx:1.23.3-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - api
      - app1
      - backlog
      - blog
      - python
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    command: sh -c "yarn install && yarn start"
    user: "${UID}:${GID}"
    restart: "no"
    env_file:
      - ".env"
    volumes:
      - ./frontend:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    command: ["rails", "server", "--binding=0.0.0.0"]
    user: "${UID}:${GID}"
    restart: "no"
    env_file:
      - ".env"
    environment:
    - HOME=/app
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app

  app1:
    image: nginx:alpine
    volumes:
      - ../app1:/usr/share/nginx/html:ro

  backlog:
    image: nginx:alpine
    volumes:
      - ../backlog:/usr/share/nginx/html:ro

  blog:
    image: nginx:alpine
    volumes:
      - ../blog:/usr/share/nginx/html:ro

  python:
    image: nginx:alpine
    volumes:
      - ../python:/usr/share/nginx/html:ro

  postgres:
    image: postgres:12.11-alpine
    env_file:
      - ".env"
    healthcheck:
      test:
        [
          "CMD", "pg_isready",
          "-q",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}",
        ]
      retries: 3
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  redis:
    image: redis:7.0-alpine
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    volumes:
      - redis-data:/data:rw
volumes:
  postgres-data:
  redis-data:
